# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Nhung/FPGA/Track/Track.srcs/sources_1/bd/test/ip/test_axi_uartlite_0_0/test_axi_uartlite_0_0.xci
# IP: The module: 'test_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Nhung/FPGA/Track/Track.gen/sources_1/bd/test/ip/test_axi_uartlite_0_0/test_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Nhung/FPGA/Track/Track.gen/sources_1/bd/test/ip/test_axi_uartlite_0_0/test_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Nhung/FPGA/Track/Track.gen/sources_1/bd/test/ip/test_axi_uartlite_0_0/test_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Nhung/FPGA/Track/Track.srcs/sources_1/bd/test/ip/test_axi_uartlite_0_0/test_axi_uartlite_0_0.xci
# IP: The module: 'test_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Nhung/FPGA/Track/Track.gen/sources_1/bd/test/ip/test_axi_uartlite_0_0/test_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Nhung/FPGA/Track/Track.gen/sources_1/bd/test/ip/test_axi_uartlite_0_0/test_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Nhung/FPGA/Track/Track.gen/sources_1/bd/test/ip/test_axi_uartlite_0_0/test_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
