set_property SRC_FILE_INFO {cfile:D:/Nhung/FPGA/Track/Track.srcs/constrs_1/new/pin_test.xdc rfile:../../../Track.srcs/constrs_1/new/pin_test.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H20 [get_ports r0_YB_0]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J20 [get_ports pulse_target_0]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N15 [get_ports pulse_delay_0]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N16 [get_ports r0_YBK_0]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L14 [get_ports strobe_1_0]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15 [get_ports strobe_2_0]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells -hier -quiet -filter {NAME =~ *cnt1_hold_reg*}] -to [get_cells -hier -quiet -filter {NAME =~ *error_reg*}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells -hier -quiet -filter {NAME =~ *cnt2_hold_reg*}] -to [get_cells -hier -quiet -filter {NAME =~ *error_reg*}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells -hier -quiet -filter {NAME =~ *ready_toggle_fast_reg*}] -to [get_cells -hier -quiet -filter {NAME =~ *ready_toggle_sync_reg*}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells -hier -quiet -filter {NAME =~ *pulse_gen_0*/*}] -to [get_cells -hier -quiet -filter {NAME =~ *discriminator_0*/*}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells -hier -quiet -filter {NAME =~ *cnt2_hold_reg*}] -to [get_cells -hier -quiet -filter {NAME =~ *has_signal_reg*}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks clk_fpga_0] -max 0.000 [get_ports {pulse_delay_0 strobe_1_0 strobe_2_0 r0_YB_0 pulse_target_0 r0_YBK_0}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks clk_fpga_0] -min 0.000 [get_ports {pulse_delay_0 strobe_1_0 strobe_2_0 r0_YB_0 pulse_target_0 r0_YBK_0}]
