#ifndef XMEM_CONFIG_H_
#define XMEM_CONFIG_H_

#define XPAR_PS7_DDR_0_BASEADDRESS 0x20000000
#define XPAR_PS7_DDR_0_HIGHADDRESS 0x3fffffff
#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0xffff

#endif