#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral MICROBLAZE_0_AXI_INTC */
#define XPAR_MICROBLAZE_0_AXI_INTC_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_MICROBLAZE_0_AXI_INTC_BASEADDR 0x41200000
#define XPAR_MICROBLAZE_0_AXI_INTC_HIGHADDR 0x41200fff
#define XPAR_MICROBLAZE_0_AXI_INTC_KIND_OF_INTR 0x2
#define XPAR_MICROBLAZE_0_AXI_INTC_IS_FAST 0x1
#define XPAR_MICROBLAZE_0_AXI_INTC_IVAR_RST_VAL 0x10
#define XPAR_MICROBLAZE_0_AXI_INTC_NUM_INTR_INPUTS 0x2
#define XPAR_MICROBLAZE_0_AXI_INTC_ADDR_WIDTH 0x20
#define XPAR_MICROBLAZE_0_AXI_INTC_OPTIONS 0x0
#define XPAR_MICROBLAZE_0_AXI_INTC_INTCTYPE 0x0
#define XPAR_MICROBLAZE_0_AXI_INTC_HANDLER_TABLE 0x0
#define XPAR_MICROBLAZE_0_AXI_INTC_NUM_SW_INTR 0x0

/* Canonical definitions for peripheral MICROBLAZE_0_AXI_INTC */
#define XPAR_XINTC_0_BASEADDR 0x41200000
#define XPAR_XINTC_0_HIGHADDR 0x41200fff
#define XPAR_XINTC_0_HANDLER_TABLE 0x0
#define XPAR_XINTC_0_ADDR_WIDTH 0x20
#define XPAR_XINTC_0_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_XINTC_0_IS_FAST 0x1
#define XPAR_XINTC_0_IVAR_RST_VAL 0x10
#define XPAR_XINTC_0_INTCTYPE 0x0
#define XPAR_XINTC_0_KIND_OF_INTR 0x2
#define XPAR_XINTC_0_NUM_INTR_INPUTS 0x2
#define XPAR_XINTC_0_NUM_SW_INTR 0x0
#define XPAR_XINTC_0_OPTIONS 0x0

#define XPAR_XUARTLITE_NUM_INSTANCES 2

/* Definitions for peripheral MDM_1 */
#define XPAR_MDM_1_COMPATIBLE "xlnx,mdm-3.2"
#define XPAR_MDM_1_BASEADDR 0x41400000
#define XPAR_MDM_1_HIGHADDR 0x41400fff
#define XPAR_MDM_1_BAUDRATE 0x0
#define XPAR_MDM_1_USE_PARITY 0x0
#define XPAR_MDM_1_ODD_PARITY 0x0
#define XPAR_MDM_1_DATA_BITS 0x0

/* Canonical definitions for peripheral MDM_1 */
#define XPAR_XUARTLITE_0_BASEADDR 0x41400000
#define XPAR_XUARTLITE_0_HIGHADDR 0x41400fff
#define XPAR_XUARTLITE_0_BAUDRATE 0x0
#define XPAR_XUARTLITE_0_COMPATIBLE "xlnx,mdm-3.2"
#define XPAR_XUARTLITE_0_DATA_BITS 0x0
#define XPAR_XUARTLITE_0_ODD_PARITY 0x0
#define XPAR_XUARTLITE_0_USE_PARITY 0x0

/* Definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_AXI_UARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_AXI_UARTLITE_0_BASEADDR 0x40600000
#define XPAR_AXI_UARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_AXI_UARTLITE_0_BAUDRATE 0x2580
#define XPAR_AXI_UARTLITE_0_USE_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_ODD_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_DATA_BITS 0x8
#define XPAR_AXI_UARTLITE_0_INTERRUPTS 0x1
#define XPAR_FABRIC_AXI_UARTLITE_0_INTR 1
#define XPAR_AXI_UARTLITE_0_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_XUARTLITE_1_BASEADDR 0x40600000
#define XPAR_FABRIC_XUARTLITE_1_INTR 1
#define XPAR_XUARTLITE_1_HIGHADDR 0x4060ffff
#define XPAR_XUARTLITE_1_BAUDRATE 0x2580
#define XPAR_XUARTLITE_1_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_XUARTLITE_1_DATA_BITS 0x8
#define XPAR_XUARTLITE_1_INTERRUPTS 0x1
#define XPAR_XUARTLITE_1_INTERRUPT_PARENT 0x41200001
#define XPAR_XUARTLITE_1_ODD_PARITY 0x0
#define XPAR_XUARTLITE_1_USE_PARITY 0x0

/* Definitions for peripheral CONTROLLER_CONNECT_0 */
#define XPAR_CONTROLLER_CONNECT_0_BASEADDR 0x43c00000
#define XPAR_CONTROLLER_CONNECT_0_HIGHADDR 0x43c00fff

/* Canonical definitions for peripheral CONTROLLER_CONNECT_0 */
#define XPAR_CONTROLLER_CONNECT_0_BASEADDR 0x43c00000
#define XPAR_CONTROLLER_CONNECT_0_HIGHADDR 0x43c00fff

/*  BOARD definition */
#define XPS_BOARD_MYS-7Z020

#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0xffff
#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 200000000

#define XPAR_MICROBLAZE_ADDR_SIZE 32

#define XPAR_MICROBLAZE_USE_STACK_PROTECTION 0

/* Number of SLRs */
#define NUMBER_OF_SLRS 0x1

/* Device ID */
#define XPAR_DEVICE_ID "7z020"

#endif  /* end of protection macro */