# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin_test.xdc

# Block Designs: bd/test/test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test || ORIG_REF_NAME==test} -quiet] -quiet

# IP: bd/test/ip/test_sync_0_0/test_sync_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_sync_0_0 || ORIG_REF_NAME==test_sync_0_0} -quiet] -quiet

# IP: bd/test/ip/test_processing_system7_0_0/test_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_processing_system7_0_0 || ORIG_REF_NAME==test_processing_system7_0_0} -quiet] -quiet

# IP: bd/test/ip/test_target_0_0/test_target_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_target_0_0 || ORIG_REF_NAME==test_target_0_0} -quiet] -quiet

# IP: bd/test/ip/test_pulse_gen_0_0/test_pulse_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_pulse_gen_0_0 || ORIG_REF_NAME==test_pulse_gen_0_0} -quiet] -quiet

# IP: bd/test/ip/test_clk_wiz_0_0/test_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_clk_wiz_0_0 || ORIG_REF_NAME==test_clk_wiz_0_0} -quiet] -quiet

# IP: bd/test/ip/test_discriminator_0_0/test_discriminator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_discriminator_0_0 || ORIG_REF_NAME==test_discriminator_0_0} -quiet] -quiet

# IP: bd/test/ip/test_controller_0_0/test_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_controller_0_0 || ORIG_REF_NAME==test_controller_0_0} -quiet] -quiet

# XDC: d:/Nhung/FPGA/Track/Track.gen/sources_1/bd/test/test_ooc.xdc
