# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin_test.xdc

# Block Designs: bd/test/test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test || ORIG_REF_NAME==test} -quiet] -quiet

# IP: bd/test/ip/test_sync_0_0/test_sync_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_sync_0_0 || ORIG_REF_NAME==test_sync_0_0} -quiet] -quiet

# IP: bd/test/ip/test_processing_system7_0_0/test_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_processing_system7_0_0 || ORIG_REF_NAME==test_processing_system7_0_0} -quiet] -quiet

# IP: bd/test/ip/test_target_0_0/test_target_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_target_0_0 || ORIG_REF_NAME==test_target_0_0} -quiet] -quiet

# IP: bd/test/ip/test_pulse_gen_0_0/test_pulse_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_pulse_gen_0_0 || ORIG_REF_NAME==test_pulse_gen_0_0} -quiet] -quiet

# IP: bd/test/ip/test_clk_wiz_0_0/test_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_clk_wiz_0_0 || ORIG_REF_NAME==test_clk_wiz_0_0} -quiet] -quiet

# IP: bd/test/ip/test_discriminator_0_0/test_discriminator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_discriminator_0_0 || ORIG_REF_NAME==test_discriminator_0_0} -quiet] -quiet

# IP: bd/test/ip/test_microblaze_0_0/test_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_microblaze_0_0 || ORIG_REF_NAME==test_microblaze_0_0} -quiet] -quiet

# IP: bd/test/ip/test_dlmb_v10_0/test_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_dlmb_v10_0 || ORIG_REF_NAME==test_dlmb_v10_0} -quiet] -quiet

# IP: bd/test/ip/test_ilmb_v10_0/test_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_ilmb_v10_0 || ORIG_REF_NAME==test_ilmb_v10_0} -quiet] -quiet

# IP: bd/test/ip/test_dlmb_bram_if_cntlr_0/test_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==test_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/test/ip/test_ilmb_bram_if_cntlr_0/test_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==test_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/test/ip/test_lmb_bram_0/test_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_lmb_bram_0 || ORIG_REF_NAME==test_lmb_bram_0} -quiet] -quiet

# IP: bd/test/ip/test_microblaze_0_axi_intc_0/test_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_microblaze_0_axi_intc_0 || ORIG_REF_NAME==test_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/test/ip/test_microblaze_0_xlconcat_0/test_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_microblaze_0_xlconcat_0 || ORIG_REF_NAME==test_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/test/ip/test_mdm_1_0/test_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_mdm_1_0 || ORIG_REF_NAME==test_mdm_1_0} -quiet] -quiet

# IP: bd/test/ip/test_rst_ps7_0_200M_0/test_rst_ps7_0_200M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_rst_ps7_0_200M_0 || ORIG_REF_NAME==test_rst_ps7_0_200M_0} -quiet] -quiet

# IP: bd/test/ip/test_controller_connect_0_0/test_controller_connect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_controller_connect_0_0 || ORIG_REF_NAME==test_controller_connect_0_0} -quiet] -quiet

# IP: bd/test/ip/test_smartconnect_0_1/test_smartconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_smartconnect_0_1 || ORIG_REF_NAME==test_smartconnect_0_1} -quiet] -quiet

# IP: bd/test/ip/test_axi_uartlite_0_0/test_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_axi_uartlite_0_0 || ORIG_REF_NAME==test_axi_uartlite_0_0} -quiet] -quiet

# XDC: d:/Nhung/FPGA/Track/Track.gen/sources_1/bd/test/test_ooc.xdc
